export interface RequiringInpatientCare {
  ["(ALL) Discharged from hospital or released from treatment"]: number;
  ["(ALL) Requiring inpatient care"]: number;
  ["(ALL) To be confirmed"]: number;
  ["(Aichi) Discharged from hospital or released from treatment"]: number;
  ["(Aichi) Requiring inpatient care"]: number;
  ["(Aichi) To be confirmed"]: number;
  ["(Akita) Discharged from hospital or released from treatment"]: number;
  ["(Akita) Requiring inpatient care"]: number;
  ["(Akita) To be confirmed"]: number;
  ["(Aomori) Discharged from hospital or released from treatment"]: number;
  ["(Aomori) Requiring inpatient care"]: number;
  ["(Aomori) To be confirmed"]: number;
  ["(Chiba) Discharged from hospital or released from treatment"]: number;
  ["(Chiba) Requiring inpatient care"]: number;
  ["(Chiba) To be confirmed"]: number;
  ["(Ehime) Discharged from hospital or released from treatment"]: number;
  ["(Ehime) Requiring inpatient care"]: number;
  ["(Ehime) To be confirmed"]: number;
  ["(Fukui) Discharged from hospital or released from treatment"]: number;
  ["(Fukui) Requiring inpatient care"]: number;
  ["(Fukui) To be confirmed"]: number;
  ["(Fukuoka) Discharged from hospital or released from treatment"]: number;
  ["(Fukuoka) Requiring inpatient care"]: number;
  ["(Fukuoka) To be confirmed"]: number;
  ["(Fukushima) Discharged from hospital or released from treatment"]: number;
  ["(Fukushima) Requiring inpatient care"]: number;
  ["(Fukushima) To be confirmed"]: number;
  ["(Gifu) Discharged from hospital or released from treatment"]: number;
  ["(Gifu) Requiring inpatient care"]: number;
  ["(Gifu) To be confirmed"]: number;
  ["(Gunma) Discharged from hospital or released from treatment"]: number;
  ["(Gunma) Requiring inpatient care"]: number;
  ["(Gunma) To be confirmed"]: number;
  ["(Hiroshima) Discharged from hospital or released from treatment"]: number;
  ["(Hiroshima) Requiring inpatient care"]: number;
  ["(Hiroshima) To be confirmed"]: number;
  ["(Hokkaido) Discharged from hospital or released from treatment"]: number;
  ["(Hokkaido) Requiring inpatient care"]: number;
  ["(Hokkaido) To be confirmed"]: number;
  ["(Hyogo) Discharged from hospital or released from treatment"]: number;
  ["(Hyogo) Requiring inpatient care"]: number;
  ["(Hyogo) To be confirmed"]: number;
  ["(Ibaraki) Discharged from hospital or released from treatment"]: number;
  ["(Ibaraki) Requiring inpatient care"]: number;
  ["(Ibaraki) To be confirmed"]: number;
  ["(Ishikawa) Discharged from hospital or released from treatment"]: number;
  ["(Ishikawa) Requiring inpatient care"]: number;
  ["(Ishikawa) To be confirmed"]: number;
  ["(Iwate) Discharged from hospital or released from treatment"]: number;
  ["(Iwate) Requiring inpatient care"]: number;
  ["(Iwate) To be confirmed"]: number;
  ["(Kagawa) Discharged from hospital or released from treatment"]: number;
  ["(Kagawa) Requiring inpatient care"]: number;
  ["(Kagawa) To be confirmed"]: number;
  ["(Kagoshima) Discharged from hospital or released from treatment"]: number;
  ["(Kagoshima) Requiring inpatient care"]: number;
  ["(Kagoshima) To be confirmed"]: number;
  ["(Kanagawa) Discharged from hospital or released from treatment"]: number;
  ["(Kanagawa) Requiring inpatient care"]: number;
  ["(Kanagawa) To be confirmed"]: number;
  ["(Kochi) Discharged from hospital or released from treatment"]: number;
  ["(Kochi) Requiring inpatient care"]: number;
  ["(Kochi) To be confirmed"]: number;
  ["(Kumamoto) Discharged from hospital or released from treatment"]: number;
  ["(Kumamoto) Requiring inpatient care"]: number;
  ["(Kumamoto) To be confirmed"]: number;
  ["(Kyoto) Discharged from hospital or released from treatment"]: number;
  ["(Kyoto) Requiring inpatient care"]: number;
  ["(Kyoto) To be confirmed"]: number;
  ["(Mie) Discharged from hospital or released from treatment"]: number;
  ["(Mie) Requiring inpatient care"]: number;
  ["(Mie) To be confirmed"]: number;
  ["(Miyagi) Discharged from hospital or released from treatment"]: number;
  ["(Miyagi) Requiring inpatient care"]: number;
  ["(Miyagi) To be confirmed"]: number;
  ["(Miyazaki) Discharged from hospital or released from treatment"]: number;
  ["(Miyazaki) Requiring inpatient care"]: number;
  ["(Miyazaki) To be confirmed"]: number;
  ["(Nagano) Discharged from hospital or released from treatment"]: number;
  ["(Nagano) Requiring inpatient care"]: number;
  ["(Nagano) To be confirmed"]: number;
  ["(Nagasaki) Discharged from hospital or released from treatment"]: number;
  ["(Nagasaki) Requiring inpatient care"]: number;
  ["(Nagasaki) To be confirmed"]: number;
  ["(Nara) Discharged from hospital or released from treatment"]: number;
  ["(Nara) Requiring inpatient care"]: number;
  ["(Nara) To be confirmed"]: number;
  ["(Niigata) Discharged from hospital or released from treatment"]: number;
  ["(Niigata) Requiring inpatient care"]: number;
  ["(Niigata) To be confirmed"]: number;
  ["(Oita) Discharged from hospital or released from treatment"]: number;
  ["(Oita) Requiring inpatient care"]: number;
  ["(Oita) To be confirmed"]: number;
  ["(Okayama) Discharged from hospital or released from treatment"]: number;
  ["(Okayama) Requiring inpatient care"]: number;
  ["(Okayama) To be confirmed"]: number;
  ["(Okinawa) Discharged from hospital or released from treatment"]: number;
  ["(Okinawa) Requiring inpatient care"]: number;
  ["(Okinawa) To be confirmed"]: number;
  ["(Osaka) Discharged from hospital or released from treatment"]: number;
  ["(Osaka) Requiring inpatient care"]: number;
  ["(Osaka) To be confirmed"]: number;
  ["(Saga) Discharged from hospital or released from treatment"]: number;
  ["(Saga) Requiring inpatient care"]: number;
  ["(Saga) To be confirmed"]: number;
  ["(Saitama) Discharged from hospital or released from treatment"]: number;
  ["(Saitama) Requiring inpatient care"]: number;
  ["(Saitama) To be confirmed"]: number;
  ["(Shiga) Discharged from hospital or released from treatment"]: number;
  ["(Shiga) Requiring inpatient care"]: number;
  ["(Shiga) To be confirmed"]: number;
  ["(Shimane) Discharged from hospital or released from treatment"]: number;
  ["(Shimane) Requiring inpatient care"]: number;
  ["(Shimane) To be confirmed"]: number;
  ["(Shizuoka) Discharged from hospital or released from treatment"]: number;
  ["(Shizuoka) Requiring inpatient care"]: number;
  ["(Shizuoka) To be confirmed"]: number;
  ["(Tochigi) Discharged from hospital or released from treatment"]: number;
  ["(Tochigi) Requiring inpatient care"]: number;
  ["(Tochigi) To be confirmed"]: number;
  ["(Tokushima) Discharged from hospital or released from treatment"]: number;
  ["(Tokushima) Requiring inpatient care"]: number;
  ["(Tokushima) To be confirmed"]: number;
  ["(Tokyo) Discharged from hospital or released from treatment"]: number;
  ["(Tokyo) Requiring inpatient care"]: number;
  ["(Tokyo) To be confirmed"]: number;
  ["(Tottori) Discharged from hospital or released from treatment"]: number;
  ["(Tottori) Requiring inpatient care"]: number;
  ["(Tottori) To be confirmed"]: number;
  ["(Toyama) Discharged from hospital or released from treatment"]: number;
  ["(Toyama) Requiring inpatient care"]: number;
  ["(Toyama) To be confirmed"]: number;
  ["(Wakayama) Discharged from hospital or released from treatment"]: number;
  ["(Wakayama) Requiring inpatient care"]: number;
  ["(Wakayama) To be confirmed"]: number;
  ["(Yamagata) Discharged from hospital or released from treatment"]: number;
  ["(Yamagata) Requiring inpatient care"]: number;
  ["(Yamagata) To be confirmed"]: number;
  ["(Yamaguchi) Discharged from hospital or released from treatment"]: number;
  ["(Yamaguchi) Requiring inpatient care"]: number;
  ["(Yamaguchi) To be confirmed"]: number;
  ["(Yamanashi) Discharged from hospital or released from treatment"]: number;
  ["(Yamanashi) Requiring inpatient care"]: number;
  ["(Yamanashi) To be confirmed"]: number;
  Date: string;
}

export interface EmargencyTransportDifficult {
  救急搬送困難事案数: number;
  終了日: string;
  開始日: string;
}
